version: '2'
services:
    rabbit-supporter:
      image: "rabbitmq:3-management"
      hostname: "rabbit"
      environment:
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
      ports:
        - "15673:15672"
        - "5673:5672"
      labels:
        NAME: "rabbitmq-supporter"
